language: node_js
node_js:
  - stable

script:
  - npm run lint
  - npm run test

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_ACCESS_TOKEN"
  skip_cleanup: true
  on:
    branch: release
